# Generated by Django 4.0.5 on 2022-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(default='', max_length=600)),
                ('longDescription', models.TextField(default='')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('techStack', models.TextField(default='')),
                ('imageurl', models.URLField(blank=True)),
                ('githubUrl', models.URLField(blank=True)),
                ('liveUrl', models.URLField(blank=True)),
            ],
        ),
    ]
