# Generated by Django 4.0.5 on 2022-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
